### PR TITLE
#184638220 Integrate HoundCI with badge attached to readme

### PR DESCRIPTION
**Pull request by Daniel-Dukundane**
#### What does this PR do?

Integrate HoundCI with badge attached to readme

#### How should this be manually tested?

- Check that the badge code is correctly inserted into your README file. You should see the badge displayed in your README file, with a link to HoundCI.
- Push your changes to your repository and wait for HoundCI to complete the analysis. You should see the HoundCI status on your pull request or commit.

#### What are the relevant pivotal tracker/Trello stories?

#184638220

### CODE REVIEW

**Review by iradukundairenee — CHANGES_REQUESTED** [review]
6 commits

**Comment by Daniel-Dukundane** [comment]
> 6 commits

The five later commits were done to test if HoundCI checks the commits, kindly consider my first commit

**Comment by iradukundairenee** [comment]
> > 6 commits
> 
> The five later commits were done to test if HoundCI checks the commits, kindly consider my first commit
yeah i know it and 6 commits are too much , please make research how to squash commit into one or 2 can better for you

**Comment by iradukundairenee** [comment]
> > > 6 commits
> > 
> > 
> > The five later commits were done to test if HoundCI checks the commits, kindly consider my first commit
> > yeah i know it but  6 commits are too much , please make research how to squash commit into one or 2 can better for you

**Comment by Daniel-Dukundane** [comment]
> > > > 6 commits
> > > 
> > > 
> > > The five later commits were done to test if HoundCI checks the commits, kindly consider my first commit
> > > yeah i know it but  6 commits are too much , please make research how to squash commit into one or 2 can better for you

Noted with Thanks

**Review by ishgervais — APPROVED** [review]

**Review by aimee-annabelle — APPROVED** [review]

**Review by iradukundairenee — APPROVED** [review]

**Review by iradukundairenee — APPROVED** [review]

**Pull request merged**
