### PR TITLE
#184638221 integrate Github actions with readme badge

### PR DESCRIPTION
**Pull request by aimee-annabelle**
What does this PR do?
=>This PR has an updated readme file that contains a badge

Description of Task to be completed
=> I have added markdown code for the build action in the readme file check if the badge appears successfully. Once the readme badge is successful I can add more GitHub actions depending on the project actions.

How should this be manually tested?
=> This can be tested on the GitHub repo by checking if a badge appear on top of the displayed texts from readme file

Any background context you want to provide?
=> No background context

What are the relevant pivot tracker story?
=> This is required to automatically run tests and other preliminary build steps required to ship the next iteration of the product

Screenshots (if appropriate) no screenshots

### CODE REVIEW

**Comment by iradukundairenee** [comment]
@aimee-annabelle  add at least 3 reviewers and remember to squash your commits into 1 commit, 4 commits are not Good

**Comment by aimee-annabelle** [comment]
I apologize for the mistake I will correct for the following commits @iradukundairenee

**Review by ishgervais — CHANGES_REQUESTED** [review]
Hey, 
remember the naming convention for the commit message
this is a  chore commit
remember this syntax:  [type]: [body]

**Comment by iradukundairenee** [comment]
@aimee-annabelle  follow this this template for writing github description
```
What does this PR do?
=>
Description of Task to be completed
=>
How should this be manually tested?
=>
Any background context you want to provide?
=>
What are the relevant pivot tracker story?
=>
Screenshots (if appropriate)
```

**Review by MerlyneIradukunda — APPROVED** [review]

**Comment by aimee-annabelle** [comment]
@iradukundairenee I did it please review and see if there are any changes I need to make. also review the codes so that I can commit new changes I've made. Thank you

**Review by iradukundairenee — APPROVED** [review]

**Review by ishgervais — APPROVED** [review]

**Pull request merged**
